package Ventanas;

import Clases.PerfilRecepcionistaClase;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos Puga
 */
public class PerfilRecepcionista extends javax.swing.JFrame {

    /**
     * Creates new form PerfilDoctor
     */
    static int id_recep;
    String nombre;
    String segundo_nombre;
    String apellido_paterno;
    String apellido_materno;
    String domicilio;
    String ciudad;
    String estado;
    String codigo_postal;
    String tel_domicilio;
    String tel_oficina;
    String tel_movil;
    String tel_extra;
    String correo_electronico;
    PerfilRecepcionistaClase p = new PerfilRecepcionistaClase();
            
    
    public PerfilRecepcionista(int id) {
        initComponents();
        id_recep=id;//id de usuario del recepcionista
        setLocationRelativeTo(null);
        setTitle("PERFIL RECEPCIONISTA");
        txtMedicoNo.setText(id+"");
        Object vector[] = p.obtenerDatosRecepcionista(id_recep);
        //JOptionPane.showMessageDialog(null,"vector: "+vector[0]);
        llenarCampos(vector);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtMedicoNo = new javax.swing.JTextField();
        txtNombre1 = new javax.swing.JTextField();
        txtNombre2 = new javax.swing.JTextField();
        txtApellido1 = new javax.swing.JTextField();
        txtApellido2 = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        txtCiudad = new javax.swing.JTextField();
        txtCodigoPostal = new javax.swing.JTextField();
        txtTelefonoOficina = new javax.swing.JTextField();
        txtTelefonoDomicilio = new javax.swing.JTextField();
        txtCorreoElectronico = new javax.swing.JTextField();
        txtTelefonoExtra = new javax.swing.JTextField();
        txtTelefonoMovil = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaDomicilio = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblNombreUsuario = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblCancelar = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblAceptar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar_32.png"))); // NOI18N
        jLabel23.setText("Guardar");
        jLabel23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel23.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Acciones");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Menu Azul.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMedicoNo.setEditable(false);
        txtMedicoNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedicoNoActionPerformed(evt);
            }
        });
        jPanel1.add(txtMedicoNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 80, -1));

        txtNombre1.setEditable(false);
        txtNombre1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombre1KeyReleased(evt);
            }
        });
        jPanel1.add(txtNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 140, -1));

        txtNombre2.setEditable(false);
        txtNombre2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombre2KeyReleased(evt);
            }
        });
        jPanel1.add(txtNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 150, -1));

        txtApellido1.setEditable(false);
        txtApellido1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtApellido1KeyReleased(evt);
            }
        });
        jPanel1.add(txtApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 140, -1));

        txtApellido2.setEditable(false);
        txtApellido2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtApellido2KeyReleased(evt);
            }
        });
        jPanel1.add(txtApellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 150, -1));

        txtEstado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEstadoKeyReleased(evt);
            }
        });
        jPanel1.add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 300, -1));

        txtCiudad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCiudadKeyReleased(evt);
            }
        });
        jPanel1.add(txtCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 300, -1));

        txtCodigoPostal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoPostalKeyReleased(evt);
            }
        });
        jPanel1.add(txtCodigoPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 110, -1));

        txtTelefonoOficina.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelefonoOficinaKeyReleased(evt);
            }
        });
        jPanel1.add(txtTelefonoOficina, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 150, -1));

        txtTelefonoDomicilio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelefonoDomicilioKeyReleased(evt);
            }
        });
        jPanel1.add(txtTelefonoDomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 150, -1));

        txtCorreoElectronico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCorreoElectronicoKeyReleased(evt);
            }
        });
        jPanel1.add(txtCorreoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, 240, -1));

        txtTelefonoExtra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelefonoExtraKeyReleased(evt);
            }
        });
        jPanel1.add(txtTelefonoExtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, 140, -1));

        txtTelefonoMovil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelefonoMovilKeyReleased(evt);
            }
        });
        jPanel1.add(txtTelefonoMovil, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, 140, -1));

        txtAreaDomicilio.setColumns(20);
        txtAreaDomicilio.setRows(5);
        txtAreaDomicilio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAreaDomicilioKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(txtAreaDomicilio);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 300, 70));

        jLabel19.setText("Correo Electronico");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, -1, 20));

        jLabel18.setText("Telefono Extra");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, -1, 20));

        jLabel17.setText("*Teléfono Movil");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, -1, 20));

        lblNombreUsuario.setText("Nombre de Usuario");
        jPanel1.add(lblNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, -1, 20));

        jLabel14.setText("Nombre de Usuario");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, -1, 20));

        jLabel12.setText("*Telefono Oficina");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, 20));

        jLabel11.setText("*Codigo Postal");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, 20));

        jLabel6.setText("Usuario No");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, 20));

        jLabel5.setText("* Nombre(s)");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, 20));

        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información de Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 420, 100));

        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información Adicional", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 420, 140));

        jLabel8.setText("* Apellido(s)");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, 20));

        jLabel7.setText("* Estado");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, 20));

        jLabel9.setText("* Domicilio");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, 20));

        jLabel10.setText("* Ciudad");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, 20));

        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 460, 440));

        jLabel13.setText("*Telefono Domicilio");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, 20));

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));
        jPanel2.setForeground(new java.awt.Color(0, 102, 153));

        lblCancelar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCancelar.setForeground(new java.awt.Color(255, 255, 255));
        lblCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cancelar_32.png"))); // NOI18N
        lblCancelar.setText("Cancelar");
        lblCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCancelarMouseClicked(evt);
            }
        });
        jPanel2.add(lblCancelar);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 300, 100, 40));

        jPanel3.setBackground(new java.awt.Color(0, 102, 153));

        lblAceptar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblAceptar.setForeground(new java.awt.Color(255, 255, 255));
        lblAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Aceptar_32.png"))); // NOI18N
        lblAceptar.setText("Aceptar");
        lblAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAceptarMouseClicked(evt);
            }
        });
        jPanel3.add(lblAceptar);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 100, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 920, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMedicoNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedicoNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedicoNoActionPerformed

    private void lblCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelarMouseClicked
        dispose();
    }//GEN-LAST:event_lblCancelarMouseClicked

    private void lblAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAceptarMouseClicked
        domicilio=txtAreaDomicilio.getText();
        ciudad=txtCiudad.getText();
        estado=txtEstado.getText();
        codigo_postal=txtCodigoPostal.getText();
        tel_domicilio=txtTelefonoDomicilio.getText();
        tel_oficina=txtTelefonoOficina.getText();
        tel_movil=txtTelefonoMovil.getText();
        tel_extra=txtCorreoElectronico.getText();
        correo_electronico=txtTelefonoExtra.getText();
        
        if(p.validarCampos(domicilio, ciudad, estado, codigo_postal, tel_domicilio, tel_oficina, tel_movil)){
        int respuesta=JOptionPane.showConfirmDialog(null, "¿Desea guardar los cambios?",
                 "Modificar perfil", JOptionPane.YES_NO_OPTION, 
                 JOptionPane.QUESTION_MESSAGE);
        if(respuesta == 0){
       p.actualizarDatosRecepcionista(domicilio, ciudad, estado, codigo_postal, tel_domicilio, tel_oficina, tel_movil, tel_extra, correo_electronico, id_recep);
       dispose(); 
        }//confirmacion y actualizacion
        }//if Validacion de datos y actualizacion
    }//GEN-LAST:event_lblAceptarMouseClicked

    private void txtAreaDomicilioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAreaDomicilioKeyReleased
        txtAreaDomicilio.setText(txtAreaDomicilio.getText().toUpperCase());
    }//GEN-LAST:event_txtAreaDomicilioKeyReleased

    private void txtCiudadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCiudadKeyReleased
    txtCiudad.setText(txtCiudad.getText().toUpperCase());        // TODO add your handling code here:
    }//GEN-LAST:event_txtCiudadKeyReleased

    private void txtEstadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEstadoKeyReleased
    txtEstado.setText(txtEstado.getText().toUpperCase());        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoKeyReleased

    private void txtCorreoElectronicoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoElectronicoKeyReleased
    txtCorreoElectronico.setText(txtCorreoElectronico.getText().toUpperCase());        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoElectronicoKeyReleased

    private void txtCodigoPostalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoPostalKeyReleased
    txtCodigoPostal.setText(txtCodigoPostal.getText().toUpperCase()); 
    p.soloNumeros(evt);// TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoPostalKeyReleased

    private void txtTelefonoDomicilioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoDomicilioKeyReleased
    txtTelefonoDomicilio.setText(txtTelefonoDomicilio.getText().toUpperCase()); 
    p.validarTelefono(evt);// TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoDomicilioKeyReleased

    private void txtTelefonoOficinaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoOficinaKeyReleased
    txtTelefonoOficina.setText(txtTelefonoOficina.getText().toUpperCase());
   p.validarTelefono(evt);// TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoOficinaKeyReleased

    private void txtTelefonoMovilKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoMovilKeyReleased
    txtTelefonoMovil.setText(txtTelefonoMovil.getText().toUpperCase());
    p.validarTelefono(evt);// TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoMovilKeyReleased

    private void txtTelefonoExtraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoExtraKeyReleased
    txtTelefonoExtra.setText(txtTelefonoExtra.getText().toUpperCase());  
    p.validarTelefono(evt);// TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoExtraKeyReleased

    private void txtNombre1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombre1KeyReleased
    txtNombre1.setText(txtNombre1.getText().toUpperCase());
    }//GEN-LAST:event_txtNombre1KeyReleased

    private void txtNombre2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombre2KeyReleased
    txtNombre2.setText(txtNombre2.getText().toUpperCase());    // TODO add your handling code here:
    }//GEN-LAST:event_txtNombre2KeyReleased

    private void txtApellido1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellido1KeyReleased
    txtApellido1.setText(txtApellido1.getText().toUpperCase());        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellido1KeyReleased

    private void txtApellido2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellido2KeyReleased
    txtApellido2.setText(txtApellido2.getText().toUpperCase());        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellido2KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PerfilRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PerfilRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PerfilRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PerfilRecepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PerfilRecepcionista(id_recep).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAceptar;
    private javax.swing.JLabel lblCancelar;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JTextField txtApellido1;
    private javax.swing.JTextField txtApellido2;
    private javax.swing.JTextArea txtAreaDomicilio;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtCodigoPostal;
    private javax.swing.JTextField txtCorreoElectronico;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtMedicoNo;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtNombre2;
    private javax.swing.JTextField txtTelefonoDomicilio;
    private javax.swing.JTextField txtTelefonoExtra;
    private javax.swing.JTextField txtTelefonoMovil;
    private javax.swing.JTextField txtTelefonoOficina;
    // End of variables declaration//GEN-END:variables
    public void llenarCampos(Object vector[]){
/*0nombre,1segundo_nombre,2apellido_paterno,3apellido_materno,4domicilio,5ciudad,
6estado,7codigo_postal,8tel_domicilio,9tel_oficina,10tel_movil,11tel_extra,12correo_electronico*/
txtNombre1.setText(vector[0]+"");
txtNombre2.setText(vector[1]+"");
txtApellido1.setText(vector[2]+"");
txtApellido2.setText(vector[3]+"");
txtAreaDomicilio.setText(vector[4]+"");
txtCiudad.setText(vector[5]+"");
txtEstado.setText(vector[6]+"");
txtCodigoPostal.setText(vector[7]+"");
txtTelefonoDomicilio.setText(vector[8]+"");
txtTelefonoOficina.setText(vector[9]+"");
txtTelefonoMovil.setText(vector[10]+"");
txtCorreoElectronico.setText(vector[11]+"");
txtTelefonoExtra.setText(vector[12]+"");
lblNombreUsuario.setText(vector[0]+" "+vector[2]);

        if(txtAreaDomicilio.getText().equals("null")){txtAreaDomicilio.setText("");}
        if(txtCiudad.getText().equals("null")){txtCiudad.setText("");}
        if(txtEstado.getText().equals("null")){txtEstado.setText("");}
        if(txtCodigoPostal.getText().equals("null")){txtCodigoPostal.setText("");}
        if(txtAreaDomicilio.getText().equals("null")){txtAreaDomicilio.setText("");}
        if(txtTelefonoDomicilio.getText().equals("null")){txtTelefonoDomicilio.setText("");}
        if(txtTelefonoOficina.getText().equals("null")){txtTelefonoOficina.setText("");}
        if(txtTelefonoMovil.getText().equals("null")){txtTelefonoMovil.setText("");}
        if(txtTelefonoExtra.getText().equals("null")){txtTelefonoExtra.setText("");}
        if(txtCorreoElectronico.getText().equals("null")){txtCorreoElectronico.setText("");}



    
    }//llenarCampos
}
