/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;
import Clases.ModificarPerfilDoctorClase;
import static Ventanas.PerfilRecepcionista.id_recep;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author Carlos Puga
 */
public class PerfilDoctor extends javax.swing.JFrame {
    
    static int id_Doctor;
    String nombre;
    String segundo_nombre;
    String apellido_paterno;
    String apellido_materno;
    String domicilio;
    String ciudad;
    String estado;
    String codigo_postal;
    String tel_domicilio;
    String tel_oficina;
    String tel_movil;
    String tel_extra;
    String correo_electronico;
    String cedula_Profecional;
    String especialidad;
    String observaciones;
    
    ModificarPerfilDoctorClase d = new ModificarPerfilDoctorClase();
    
    
    /**
     * Creates new form PerfilDoctor
     */
    public PerfilDoctor(int id) {
        initComponents();
         id_Doctor=id;//id de usuario del doctor
        setLocationRelativeTo(null);
        setTitle("PERFIL DOCTOR");
        txtMedicoNo.setText(id+"");
        Object vector[] = d.obtenerDatosDoctor(id_Doctor);
        llenarCampos(vector);
        txtNombre1.enable(false);
        txtNombre2.enable(false);
        txtApellido1.enable(false);
        txtApellido2.enable(false);
        txtMedicoNo.enable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel23 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtMedicoNo = new javax.swing.JTextField();
        txtNombre1 = new javax.swing.JTextField();
        txtNombre2 = new javax.swing.JTextField();
        txtApellido1 = new javax.swing.JTextField();
        txtApellido2 = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        txtCiudad = new javax.swing.JTextField();
        txtCodigoPostal = new javax.swing.JTextField();
        txtTelefonoOficina = new javax.swing.JTextField();
        txtTelefonoDomicilio = new javax.swing.JTextField();
        txtTelefonoExtra = new javax.swing.JTextField();
        txtCedulaProfesional = new javax.swing.JTextField();
        txtCorreoElectronico = new javax.swing.JTextField();
        txtTelefonoMovil = new javax.swing.JTextField();
        txtAreaObservaciones = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaDomicilio = new javax.swing.JTextArea();
        txtAreaEspecialidad = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar_32.png"))); // NOI18N
        jLabel23.setText("Guardar");
        jLabel23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel23.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        jLabel23.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLabel23KeyReleased(evt);
            }
        });
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 20, 80));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Acciones");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Menu Azul.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMedicoNo.setEditable(false);
        txtMedicoNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedicoNoActionPerformed(evt);
            }
        });
        jPanel1.add(txtMedicoNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 80, -1));

        txtNombre1.setEditable(false);
        jPanel1.add(txtNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 140, -1));

        txtNombre2.setEditable(false);
        jPanel1.add(txtNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 150, -1));

        txtApellido1.setEditable(false);
        jPanel1.add(txtApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 140, -1));

        txtApellido2.setEditable(false);
        jPanel1.add(txtApellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 150, -1));

        txtEstado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEstadoKeyReleased(evt);
            }
        });
        jPanel1.add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 300, -1));

        txtCiudad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCiudadKeyReleased(evt);
            }
        });
        jPanel1.add(txtCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 300, -1));
        jPanel1.add(txtCodigoPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 110, -1));
        jPanel1.add(txtTelefonoOficina, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 150, -1));
        jPanel1.add(txtTelefonoDomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 150, -1));
        jPanel1.add(txtTelefonoExtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 210, 240, -1));

        txtCedulaProfesional.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCedulaProfesionalKeyReleased(evt);
            }
        });
        jPanel1.add(txtCedulaProfesional, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 240, 240, -1));
        jPanel1.add(txtCorreoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 180, 140, -1));
        jPanel1.add(txtTelefonoMovil, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 150, 140, -1));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextArea2KeyReleased(evt);
            }
        });
        txtAreaObservaciones.setViewportView(jTextArea2);

        jPanel1.add(txtAreaObservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 350, 240, 70));

        txtAreaDomicilio.setColumns(20);
        txtAreaDomicilio.setRows(5);
        txtAreaDomicilio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAreaDomicilioKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(txtAreaDomicilio);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 300, 70));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextArea1KeyReleased(evt);
            }
        });
        txtAreaEspecialidad.setViewportView(jTextArea1);

        jPanel1.add(txtAreaEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 270, 240, 70));

        jLabel22.setText("Observaciones");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, -1, 20));

        jLabel21.setText("*Especialidad");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, -1, 20));

        jLabel20.setText("*Cedula Profesional");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, -1, 20));

        jLabel19.setText("Correo Electronico");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, -1, 20));

        jLabel18.setText("Telefono Extra");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, -1, 20));

        jLabel17.setText("*Teléfono Movil");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, -1, 20));

        jLabel15.setText("Nombre de Usuario");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 50, -1, 20));

        jLabel14.setText("Nombre de Usuario");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, -1, 20));

        jLabel12.setText("*Telefono Oficina");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, 20));

        jLabel11.setText("*Codigo Postal");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, 20));

        jLabel6.setText("Usuario No");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, 20));

        jLabel5.setText("Nombre(s)");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, 20));

        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información de Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 440, 100));

        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información Adicional", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 440, 330));

        jLabel8.setText("Apellido(s)");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, 20));

        jLabel7.setText("*Estado");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, 20));

        jLabel9.setText("*Domicilio");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, 20));

        jLabel10.setText("*Ciudad");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, 20));

        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Médico", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 500, 440));

        jLabel13.setText("*Telefono Domicilio");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1000, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMedicoNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedicoNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedicoNoActionPerformed

    private void jLabel23KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel23KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel23KeyReleased

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        domicilio=txtAreaDomicilio.getText();
        ciudad=txtCiudad.getText();
        estado=txtEstado.getText();
        codigo_postal=txtCodigoPostal.getText();
        tel_domicilio=txtTelefonoDomicilio.getText();
        tel_oficina=txtTelefonoOficina.getText();
        tel_movil=txtTelefonoMovil.getText();
        tel_extra=txtCorreoElectronico.getText();
        correo_electronico=txtTelefonoExtra.getText();
        cedula_Profecional=txtCedulaProfesional.getText();
        especialidad=jTextArea1.getText();
        observaciones=jTextArea2.getText();
        
        if(d.validarCampos(domicilio, ciudad, estado, codigo_postal, tel_domicilio, tel_oficina, tel_movil, cedula_Profecional, especialidad)){
        int respuesta=JOptionPane.showConfirmDialog(null, "¿Desea guardar los cambios?",
                 "Modificar perfil", JOptionPane.YES_NO_OPTION, 
                 JOptionPane.QUESTION_MESSAGE);
        if(respuesta == 0){
       d.actualizarDatosDoctor(domicilio, ciudad, estado, codigo_postal, tel_domicilio, tel_oficina, tel_movil, tel_extra, correo_electronico, cedula_Profecional,especialidad, observaciones, id_Doctor);
       dispose(); 
        }//confirmacion y actualizacion
        }//if Validacion de datos y actualizacion
    }//GEN-LAST:event_jLabel23MouseClicked

    private void txtAreaDomicilioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAreaDomicilioKeyReleased
        txtAreaDomicilio.setText(txtAreaDomicilio.getText().toUpperCase());// TODO add your handling code here:
    }//GEN-LAST:event_txtAreaDomicilioKeyReleased

    private void txtCiudadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCiudadKeyReleased
        txtCiudad.setText(txtCiudad.getText().toUpperCase());        // TODO add your handling code here:
    }//GEN-LAST:event_txtCiudadKeyReleased

    private void txtEstadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEstadoKeyReleased
    txtEstado.setText(txtEstado.getText().toUpperCase());        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoKeyReleased

    private void txtCedulaProfesionalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaProfesionalKeyReleased
        txtCedulaProfesional.setText(txtCedulaProfesional.getText().toUpperCase());        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaProfesionalKeyReleased

    private void jTextArea1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyReleased
    jTextArea1.setText(jTextArea1.getText().toUpperCase());    // TODO add your handling code here:
    }//GEN-LAST:event_jTextArea1KeyReleased

    private void jTextArea2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea2KeyReleased
    jTextArea2.setText(jTextArea2.getText().toUpperCase());          // TODO add your handling code here:
    }//GEN-LAST:event_jTextArea2KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PerfilDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PerfilDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PerfilDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PerfilDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PerfilDoctor(id_Doctor).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField txtApellido1;
    private javax.swing.JTextField txtApellido2;
    private javax.swing.JTextArea txtAreaDomicilio;
    private javax.swing.JScrollPane txtAreaEspecialidad;
    private javax.swing.JScrollPane txtAreaObservaciones;
    private javax.swing.JTextField txtCedulaProfesional;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtCodigoPostal;
    private javax.swing.JTextField txtCorreoElectronico;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtMedicoNo;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtNombre2;
    private javax.swing.JTextField txtTelefonoDomicilio;
    private javax.swing.JTextField txtTelefonoExtra;
    private javax.swing.JTextField txtTelefonoMovil;
    private javax.swing.JTextField txtTelefonoOficina;
    // End of variables declaration//GEN-END:variables
public void llenarCampos(Object vector[]){
/*0nombre,1segundo_nombre,2apellido_paterno,3apellido_materno,4domicilio,5ciudad,
6estado,7codigo_postal,8tel_domicilio,9tel_oficina,10tel_movil,11tel_extra,12correo_electronico*/
txtNombre1.setText(vector[0]+"");
txtNombre2.setText(vector[1]+"");
txtApellido1.setText(vector[2]+"");
txtApellido2.setText(vector[3]+"");
txtAreaDomicilio.setText(vector[4]+"");
txtCiudad.setText(vector[5]+"");
txtEstado.setText(vector[6]+"");
txtCodigoPostal.setText(vector[7]+"");
txtTelefonoDomicilio.setText(vector[8]+"");
txtTelefonoOficina.setText(vector[9]+"");
txtTelefonoMovil.setText(vector[10]+"");
txtTelefonoExtra.setText(vector[11]+"");
txtCorreoElectronico.setText(vector[12]+"");
txtCedulaProfesional.setText(vector[13]+"");
jTextArea1.setText(vector[14]+"");
jTextArea2.setText(vector[15]+"");
jLabel15.setText(" "+vector[0]+" "+vector[2]);


        if(txtAreaDomicilio.getText().equals("null")){txtAreaDomicilio.setText("");}
        if(txtCiudad.getText().equals("null")){txtCiudad.setText("");}
        if(txtEstado.getText().equals("null")){txtEstado.setText("");}
        if(txtCodigoPostal.getText().equals("null")){txtCodigoPostal.setText("");}
        if(txtTelefonoDomicilio.getText().equals("null")){txtTelefonoDomicilio.setText("");}
        if(txtTelefonoOficina.getText().equals("null")){txtTelefonoOficina.setText("");}
        if(txtTelefonoMovil.getText().equals("null")){txtTelefonoMovil.setText("");}
        if(txtTelefonoExtra.getText().equals("null")){txtTelefonoExtra.setText("");}
        if(txtCorreoElectronico.getText().equals("null")){txtCorreoElectronico.setText("");}
        if(txtCedulaProfesional.getText().equals("null")){txtCedulaProfesional.setText("");}
        if(jTextArea1.getText().equals("null")){jTextArea1.setText("");}
        if(jTextArea2.getText().equals("null")){jTextArea2.setText("");}
}//llenarCampos
    

}
